
require "spec"

require "../src/pratt"
# require "expressions/assign_expression"
# require "../src/expressions/call_expression"
# require "../src/expressions/conditional_expression"
# require "../src/expressions/postfix_expression"
# require "../src/expressions/prefix_expression"
# require "../src/lexer"
# require "../src/parselets/assign_parselet"
# require "../src/parselets/assign_parselet"
# require "../src/parselets/binary_operator_parselet"
# require "../src/parselets/call_parselet"
# require "../src/parselets/conditional_parselet"
# require "../src/parselets/group_parselet"
# require "../src/parselets/infix_parselet"
# require "../src/parselets/name_parselet"
# require "../src/parselets/postfix_operator_parselet"
# require "../src/parselets/prefix_operator_parselet"
# require "../src/parser"
# require "../src/pratt"
# require "../src/token"
# require "../src/tokentype"

