
require "./tokentype"

module Pratt
  # A simple token class. These are generated by Lexer and consumed by Parser.
  struct Token
    property mType : TokenType::Type
    property mText : String

    def initialize(@mType, @mText)
    end
  end
end

