
require "./tokentype"

module Pratt
  # A simple token class. These are generated by Lexer and consumed by Parser.
  struct Token
    property m_type : TokenType::Type
    property m_text : String

    def initialize(@m_type, @m_text)
    end
  end
end

